### PR TITLE
#163556722 implement endpoint for getting a specific party

### PR DESCRIPTION
**Pull request by Bobjayafam**
#### What does this PR do?
Implement an API endpoint for getting a specific political party
#### Description of Task to be completed?
-write middleware for validating the party id
- add a get one party method for the route
- write tests for the endpoint
#### How should this be manually tested?
- clone the GitHub repo
- checkout branch ``ft-admin-get-party-163556722``
- on POSTMAN, send a GET request to ``/api/v1/parties/:id``. The response should be the specific party with a status code of 200.
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/163556722

### CODE REVIEW

**Comment by Bobjayafam** [comment]
@akinwale-habibullah kindly review

**Review by akinwale-habibullah — COMMENTED** [review]
In your server.js file, port = process.env.PORT. What happens when I fail to configure a port. Add a default port as a fallback.

**Comment by akinwale-habibullah** [comment]
Each resource should have a route file. For instance, parties should have a parties routes file instead of lumping everything together.

**Review by akinwale-habibullah — APPROVED** [review]
Please add make the changes I highlighted and go ahead to merge. Good job 👍

**Comment by Bobjayafam** [comment]
I have made the changes, thanks.

**Pull request merged**
